require_relative '../book'
require_relative '../person'
require_relative '../student'
require_relative '../teacher'
require_relative '../capitalize'
require_relative '../trimmer'
require_relative '../classroom'
require_relative '../rental'
